config/routes.rb
Oljournal::Application.routes.draw do
  resources :days

  devise_for :users, :controllers => {:registrations => "registrations"}           #http://stackoverflow.com/questions/3546289/override-devise-registrations-controller

  root 'page#index'
  get 'about' => 'page#about'
  get 'inspiration' => 'page#inspiration'
  get 'poll' => 'page#poll'

  get 'journal', to: 'days#index'
  post 'welcome', to: 'page#begin_user_onboard'
  get 'finish', to: 'days#finish_user_onboard'
  post 'finish', to: 'days#finish_user_onboard'

  post 'gcm', to: 'page#send_gcm'

  namespace :api do
    namespace :v1 do
      resources :tokens,:only => [:create, :destroy]
      resources :mobiles
      post 'mobiles/addday', to: 'mobiles#addday'
      post 'mobiles/alldays', to: 'mobiles#alldays'
      post 'mobiles/editday', to: 'mobiles#editday'
      post 'mobiles/gcmregid', to: 'mobiles#gcmregid'
    end
  end
end

app/models/day.rb
class Day < ActiveRecord::Base
  default_scope { order('date DESC') }
  belongs_to :user
  validates_uniqueness_of :date, scope: [:user_id]

  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      #csv << column_names
      column_names = %w(date content)
      csv << column_names
      all.each do |day|
        csv << day.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_day, only: [:show, :edit, :update, :destroy]

  def finish_user_onboard
    @day = Day.create(:date => Day.new, :content => session['day'], :user_id => current_user )
    @day.save
    redirect_to('/journal')
  end

  # GET /days
  # GET /days.json
  def index
    #@days = Day.all
    @day_user = current_user
    @days = @day_user.days
    respond_to do |format|
      format.html
      format.csv { send_data @days.to_csv }
      format.xls # { send_data @products.to_csv(col_sep: "\t") }
    end
  end

  # GET /days/1
  # GET /days/1.json
  def show
    @day = current_user.days.find(params[:id])
  end

  # GET /days/new
  def new
    @day = Day.new
    @day_user = current_user
    @day.user_id = @day_user.id
  end

  # GET /days/1/edit
  def edit
  end

  # POST /days
  # POST /days.json
  def create
    @day = Day.new(day_params)

    respond_to do |format|
      if @day.save
        format.html { redirect_to '/journal', notice: 'Day was successfully created.' }
        format.json { render action: 'show', status: :created, location: @day }
      else
        format.html { render action: 'new' }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /days/1
  # PATCH/PUT /days/1.json
  def update
    respond_to do |format|
      if @day.update(day_params)
        format.html { redirect_to '/journal', notice: 'Day was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /days/1
  # DELETE /days/1.json
  def destroy
    @day.destroy
    respond_to do |format|
      format.html { redirect_to days_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day
      @day = Day.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_params
      params.require(:day).permit(:date, :content, :user_id)
    end
end

app/helpers/days_helper.rb
module DaysHelper
  def get_date_text(day)
    day_int = day.date.wday
    case day_int
      when 0
        day_string = 'Sun'
      when 1
        day_string = 'Mon'
      when 2
        day_string = 'Tue'
      when 3
        day_string = 'Wed'
      when 4
        day_string = 'Thr'
      when 5
        day_string = 'Fri'
      else
        day_string = 'Sat'
    end
    @date_string = day_string + ', ' + day.date.to_s
  end
end

app/views/days/_form.html.erb
<%= form_for(@day) do |f| %>
  <% if @day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@day.errors.count, "error") %> prohibited this day from being saved:</h2>

      <ul>
      <% @day.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :date %><br>
    <%= f.date_select :date, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: "form-control" %>
  </div>
    <%= f.hidden_field :user_id %>
  <div class="actions">
    <button type="submit" name="commit" class="btn btn-default">Update Day</button>
  </div>
<% end %>

app/views/days/edit.html.erb
<div class="container">
  <h1>Editing day</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @day %> |
  <%= link_to 'Back', '/journal' %>
</div>

app/views/days/index.html.erb
<div class="container">
  <h1>Journal</h1>
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Date</th>
      <th>Content</th>
      <!--<th>Owner</th>-->
      <th></th>
      <th></th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% @days.each do |day| %>
        <tr>
          <td class="col-sm-2"><%= get_date_text(day) %></td>
          <td class = "col-sm-8"><%= day.content %></td>
          <!--<td><%= day.user_id %></td>-->
          <!--<td class = "col-sm-1"><%= link_to 'Show', day %></td>-->
          <td class = "col-sm-1"><%= link_to 'Edit', edit_day_path(day) %></td>
          <td class = "col-sm-1"><%= link_to 'Destroy', day, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Day', new_day_path %>
</div>

app/views/days/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:o="urn:schemas-microsoft-com:office:office"
          xmlns:x="urn:schemas-microsoft-com:office:excel"
          xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
          xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">Date</Data></Cell>
        <Cell><Data ss:Type="String">Content</Data></Cell>
      </Row>
      <% @days.each do |day| %>
          <Row>
            <Cell><Data ss:Type="String"><%= day.date %></Data></Cell>
            <Cell><Data ss:Type="String"><%= day.content %></Data></Cell>
          </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/days/new.html.erb
<div class="container">
  <h1>New day</h1>

  <%= render 'form' %>

  <%= link_to 'Back', '/journal' %>
</div>

app/views/days/show.html.erb
<div class="container">
  <!--<p id="notice"><%= notice %></p>-->

  <p>
    <strong>Date:</strong>
    <%= @day.date %>
  </p>

  <p>
    <strong>Content:</strong>
    <%= @day.content %>
  </p>

<!--  <p>
    <strong>Owner:</strong>
    <%= @day.user_id %>
  </p>-->

  <%= link_to 'Edit', edit_day_path(@day) %> |
  <%= link_to 'Back', '/journal' %>
</div>